[package]
name = "GLUE"
version = "0.1.0"
edition = "2021"
authors = ["Ant, O. Greene <Reel0112358.13@proton.me>"]
description = "GLUE: Genetic Language for Unsupervised Evolution in Robotics"
repository = "https://github.com/HermiTech-LLC/Glue"
license = "GNU Affero v3"

[dependencies]
# Core dependencies
regex = "1.5"
anyhow = "1.0"
lazy_static = "1.4"

# LLVM for IR generation
inkwell = { version = "0.1", features = ["llvm11-0"] } # Update based on LLVM version

# Machine learning and deep learning
tch = "0.4" # Rust bindings to PyTorch
tensorflow = "0.17" # Rust bindings for TensorFlow

# Genetic algorithms
genetic-algorithm = "0.2"

# Robotics-related dependencies
robotics = "0.3"
rosc = "0.6" # For ROS (Robot Operating System) integration

# Async runtime for concurrency
tokio = { version = "1", features = ["full"] }

# JSON for configuration and serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Mathematical computations
nalgebra = "0.29" # For linear algebra
num = "0.4"       # Provides a collection of numeric types and traits
rug = "1.13"      # For arbitrary-precision arithmetic

# Custom library or bindings for Hehner's unified algebra (hypothetical)
hehners_unified_algebra = "0.1"

[features]
default = []
# Add custom features for conditional compilation if needed

[workspace]
# List other crates in your workspace if part of a larger project

# Optional sections: [bin], [build-dependencies], [dev-dependencies], [target.'cfg(...)'.dependencies]
# can be added for multiple binary targets, build scripts, dev tools, and platform-specific dependencies
