[package]
name = "GLUE"
version = "0.1.0"
edition = "2021"
authors = ["Ant, O. Greene <Reel0112358.13@proton.me>"]
description = "GLUE: Genetic Language for Unsupervised Evolution in Robotics"
repository = "https://github.com/HermiTech-LLC/Glue"
license = "GNU Affero v3"

[dependencies]
regex = { version = "1.6", features = ["unicode", "perf"] }  # Enhanced for unicode support and performance
anyhow = "1.0"
lazy_static = "1.4"
inkwell = { version = "0.2", features = ["llvm12-0"] }  # LLVM support
tch = "0.5"                 # Torch bindings for Rust
tensorflow = "0.18"         # TensorFlow bindings for Rust
genetic-algorithm = "0.3"   # For implementing genetic algorithms
robotics = "0.4"            # For robotics functionality
rosc = "0.7"                # ROS integration
tokio = { version = "1.10", features = ["full"] }  # Async runtime
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
nalgebra = "0.30"           # For linear algebra
num = "0.4"                 # For numerical operations
rug = "1.14"                # For arbitrary precision arithmetic
hehners_unified_algebra = "0.2"  # Custom library for Hehner algebra
rayon = "1.5"               # Parallelism framework

# Optional dependencies for extended functionality
[optional-dependencies]
wasm-bindgen = "0.2"        # For WebAssembly support
pyo3 = { version = "0.15", features = ["extension-module"] }  # For Python integration

[features]
default = []
simd = ["nalgebra/simd", "rayon/simd"]  # SIMD optimizations
wasm = ["wasm-bindgen"]     # WebAssembly feature
python = ["pyo3"]           # Python integration

[workspace]
# paths to other crates in a multi-crate project

# Custom build scripts and additional settings can be added here